// <auto-generated />
using System;
using CoffeeRecordsIdentity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeRecordsIdentity.Migrations
{
    [DbContext(typeof(CoffeeRecordsIdentityContext))]
    [Migration("20260322190305_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("CoffeeRecordsIdentity.Models.CoffeeCup", b =>
                {
                    b.Property<int>("CoffeeCupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("MachineNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CoffeeCupId");

                    b.ToTable("Cups");
                });
#pragma warning restore 612, 618
        }
    }
}
